sudo: required

language: bash

env:
  - ARCH=amd64
#  - ARCH=armhf CHROOT_DIR=/tmp/chroot

services:
  - docker

before_install:
  - if [ "${ARCH}" = "armhf" ]; then
      ./setup-chroot-armhf.sh;
      sudo chroot ${CHROOT_DIR} bash -c "echo 'Environment - $(uname -a)'";
    else
      echo "Environment - $(uname -a)";
    fi

install:
  - if [ "${ARCH}" = "armhf" ]; then
      sudo chroot ${CHROOT_DIR} bash -c "cd ${TRAVIS_BUILD_DIR} && docker build -t syphr/webtts:${ARCH} -f Dockerfile.${ARCH} .";
      sudo chroot ${CHROOT_DIR} docker run -d -p 127.0.0.1:80:80 syphr/webtts:${ARCH};
      sudo chroot ${CHROOT_DIR} docker ps;
    else
      docker build -t syphr/webtts:${ARCH} -f Dockerfile.${ARCH} .;
      docker run -d -p 127.0.0.1:80:80 syphr/webtts:${ARCH};
      docker ps;
    fi

script:
  - export TEST_HOST=127.0.0.1 && ./test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "${ARCH}" = "armhf" ]; then
        sudo chroot ${CHROOT_DIR} docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
        sudo chroot ${CHROOT_DIR} docker push syphr/webtts:${ARCH};
      else
        docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
        docker push syphr/webtts:${ARCH};
      fi
    fi

